const routesMap = {
  "": "Inicio",
  "rutas-rectorado": "Rectorado",
  "rutas-vicerrectorado": "Vicerrectorado", 
  "fac-ingenieria": "Facultad de Ingeniería",
  "fac-ciencias-juridicas": "Facultad de Derecho",
  "/rutas-rectorado/secretaria-general": "Secretaría General",
  "/rutas-rectorado/comision-economica": "Comisión Económica",
  "/rutas-rectorado/comision-economica/dir-plan-univ": "Dir. de Planificación Universitaria",
  "/rutas-rectorado/comision-economica/dir-adm-fin": "Dir. de Administración y Finanzas",
  "dep-fin": "Depto. Finanzas",
  "academica": "Dirección Académica",
   facultades: "Facultades",
   "fac-derecho": "Facultad de Derecho",
  "fac-ing-geo": "Facultad de Ingeniería Geológica",
  "fac-ing-min": "Facultad de Ingeniería Minera",
  "fac-cien-agri-pec": "Facultad de Ciencias Agrarias y Pecuarias",
  "fac-ing": "Facultad de Ingeniería",
  "fac-cien-pur": "Facultad de Ciencias Puras",
  "fac-cien-eco-fin-adm": "Facultad de Ciencias Económicas, Financieras y Administrativas",
  "fac-cien-soc-hum": "Facultad de Ciencias Sociales y Humanas",
  "fac-ing-tec": "Facultad de Ingeniería Técnica",
  "fac-art": "Facultad de Artes",
  "fac-med": "Facultad de Medicina",
  "fac-cien-sal": "Facultad de Ciencias de la Salud",
  "div-administrativa": "División Administrativa",
  "administrativa": "Dirección Administrativa",
  "dir-serv-acad": "Dirección de Servicios Académicos",
};
export default routesMap;
